### ISSUE TITLE
How to open tooltip?

### ISSUE THREAD

**Issue by yonesko** [d-rk/cron-descriptor#2]
I created constant 
```java 
public static final String CRON = "0 15 10 ? * MON-FRI";
```
But desired tooltip did not opened.
What keys to press on my Mac OS?

Thanks

**Comment by d-rk** [comment]
you have to hover over the expression with the mouse, then the tooltip will apear

**Comment by benchdoos** [comment]
Does it support `yml` files?
```cleanupOldRecords: '0 0 3 * * SAT' # every Saturday at 3 am```
Not opening on hover -`IntelliJ IDEA 2020.2 (Ultimate Edition) Build #IU-202.6397.94, built on July 27, 2020`
